CREATE TABLE zoo(
    zoo_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    money NUMBER,
    available_places NUMBER
);

INSERT INTO zoo(money, available_places) VALUES(5000, 10);

CREATE TABLE animals(
    animal_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind VARCHAR(50) NOT NULL,
    diet VARCHAR(50) NOT NULL,
    gender VARCHAR(6) NOT NULL,
    color VARCHAR(10) DEFAULT 'NO_COLOR',
    price NUMBER NOT NULL,
    zoo_id_fk NUMBER REFERENCES zoo(zoo_id) NOT NULL
);